config/routes.rb
Rails.application.routes.draw do
  resources 'sections'
  resources 'lessons'
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section

  validates :name, presence: true
  validates :body, presence: true
  validates :order_number, presence: true
  # validates :order_number, uniqueness: true  #no longer using once sections are added.
  default_scope { order('order_number') }

  def next
    # find all lessons where section id is the same
    lessons_array = []
    Lesson.where(section_id: self.section_id).find_each do |lesson|
      lessons_array.push(lesson)
    end
    #   of those, find lesson with order number + 1 and return
    lessons_array.each do |lesson|
      if lesson.order_number == self.order_number + 1
        return lesson
      end
    end
    return self
  end

  def previous
    # find all lessons where section id is the same
    lessons_array = []
    Lesson.where(section_id: self.section_id).find_each do |lesson|
      lessons_array.push(lesson)
    end
    #   of those, find lesson with order number - 1 and return
    lessons_array.each do |lesson|
      if lesson.order_number == self.order_number - 1
        return lesson
      end
    end
    return self
  end


end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :lessons

  validates :name, presence: true
  validates :name, uniqueness: true
  default_scope { order('created_at') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    @lessons = Lesson.all
  end

  def new
    @lesson = Lesson.new
    sections = Section.all
    @section_option_array = []
    sections.each do |section|
      @section_option_array.push([section.name, section.id])
    end
  end

  def create
    @lesson = Lesson.new(lesson_params)
    if @lesson.save
      section = Section.find(params[:section_id])
      section.lessons.push(@lesson)
      flash[:alert] = "YOU MADE A LESSON, WAY TO GO FRIEND"
      redirect_to lessons_path
    else
      render :new
    end
  end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    redirect_to lessons_path
  end

  def edit
    sections = Section.all
    @section_option_array = []
    sections.each do |section|
      @section_option_array.push([section.name, section.id])
    end
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
    if @lesson.update(lesson_params)
      redirect_to lesson_path(@lesson)
    end
  end

  private def lesson_params
    params.require(:lesson).permit(:name, :body, :order_number, :video)
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  def index
    @sections = Section.all
  end

  def new
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)
    if @section.save
      flash[:alert] = "YOU MADE A LESSON, WAY TO GO FRIEND"
      redirect_to sections_path
    else
      render :new
    end
  end

  def show
    @section = Section.find(params[:id])
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    redirect_to sections_path
  end

  def edit
    @section = Section.find(params[:id])
  end

  def update
    @section = Section.find(params[:id])
    if @section.update(section_params)
      redirect_to section_path(@section)
    end
  end

  private def section_params
    params.require(:section).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
 <h3>You done messed up.</h3>
 <ul>
   <% object.errors.full_messages.each do |message| %>
   <li><%= message %></li>
   <% end %>
 </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container">
      <%= yield %>
    </div>
    <div class="text-center">
      <%= flash[:alert] %>
    </div>
    <nav class='navbar navbar-default' role='navigation' id="nav-footer">
      <ul class='nav navbar-nav'>
        <li><%= link_to "Lessons", lessons_path %></li>
        <li><%= link_to "Add Lesson", new_lesson_path %></li>
        <li><%= link_to "Sections", sections_path %></li>
        <li><%= link_to "Add Section", new_section_path %></li>
      </ul>
    </nav>
  </body>
</html>

app/views/lessons/_form.html.erb
<%= render "layouts/errors", object: @lesson %>
<div class="text-center">

<%= form_for @lesson do |l| %>

<%= l.label :name %>
<%= l.text_field :name, :class => "form-control" %>

<%= l.label :body  %>
<%= l.text_area :body, :class => "form-control"%>

<%= l.label :video %>
<%= l.text_field :video, :class => "form-control" %>

<%= l.label :order_number %>
<%= l.text_field :order_number, :class => "form-control" %>

<%= l.label :section_id %>
<%= select_tag(:section_id, options_for_select(@section_option_array), :class => "form-control") %>
<br>
<%= l.submit :class => "btn btn-large"  %>
</div>

<% end %>

app/views/lessons/edit.html.erb
<% content_for(:title, @lesson.name + " | Edit")  %>

<h1>Edit Lesson</h1>

<%= render "form" %>

app/views/lessons/index.html.erb
<% content_for(:title, "Lessons | PROGRAMAJAMA")  %>
<h1>Lessons</h1>

<div class="panel panel-default">

<ul class="list-group">
  <% @lessons.each do |lesson| %>
    <li class="list-group-item">
      <%= lesson.order_number %> -
      <%= link_to lesson.name, lesson_path(lesson) %>
      <span style="float: right"><%= link_to "Delete", lesson_path(lesson), data: {confirm: "YOU SURE DAWG?", method: "delete" } %>
      | <%= link_to "Edit", edit_lesson_path(lesson) %></span>
      </li>
  <% end %>
</ul>
</div>

app/views/lessons/new.html.erb
<% content_for(:title, "Lessons | New")  %>

<h1>New Lesson</h1>

<%= render "form" %>

app/views/lessons/show.html.erb
<% content_for(:title, @lesson.name + " | PROGRAMAJAMA") %>

<h1><%= @lesson.name %></h1>
<div class="panel panel-default">
  <div class="panel-body text-center">
    <iframe width="640", height="480", frameborder="0", src="<%= @lesson.video %>"></iframe>
  </div>
  <div class="panel-footer text-center">
    <p>
      <%= @lesson.body %>
    </p>
    <span style="float: left;"><%= link_to "Previous Lesson", lesson_path(@lesson.previous) %></span>
    <span style="float: right;"><%= link_to "Next Lesson", lesson_path(@lesson.next) %></span>
    <br>
  </div>


</div>

app/views/sections/_form.html.erb
<%= render "layouts/errors", object: @section %>

<%= form_for @section do |l| %>
<%= l.label :name %>
<%= l.text_field :name %>
<%= l.submit %>

<% end %>

app/views/sections/edit.html.erb
<% content_for(:title, @section.name + " | Edit")  %>

<h1>Edit Section</h1>

<%= render "form" %>

app/views/sections/index.html.erb
<% content_for(:title, "PROGRAMAJAMA")  %>
<h1>Sections</h1>

<div class="panel panel-default">

<ul class="list-group">

  <% @sections.each do |section| %>
    <li class="list-group-item section" id="section<%= section.id %>">
      <span class="section-name" data-toggle="collapse" data-target=".section<%=section.id%>"><%= section.name %></span>
      <!-- <%= link_to section.name, section_path(section) %> -->
      <span style="float: right"><%= link_to "Delete", section_path(section), data: {confirm: "YOU SURE DAWG?", method: "delete" } %>
      | <%= link_to "Edit", edit_section_path(section) %></span>
      </li>

      <ul class="sectionLessons">

      <% section.lessons.each do |lesson| %>
        <li class="section<%=section.id%> lesson-li collapse">
            <%= link_to lesson.name, lesson_path(lesson) %>
        </li>
      <% end %>

      </ul>

  <% end %>

</ul>
</div>

app/views/sections/new.html.erb
<% content_for(:title, "Sections | New")  %>

<h1>New Section</h1>

<%= render "form" %>

app/views/sections/show.html.erb
<% content_for(:title, @section.name + " | PROGRAMAJAMA") %>

<h1><%= @section.name %></h1>
<% @section.lessons.each do |lesson| %>
  <p>
    <%= link_to lesson.name, lesson_path(lesson) %>
  </p>
<% end %>